discourse/discourse_api

examples/update_user.rb
lib/discourse_api/api/users.rb

Feature request on [meta](https://meta.discourse.org/t/how-can-i-update-trust-level-via-sso-site/23876?u=techapj)

FEATURE: update user trust level

---

examples/groups.rb
lib/discourse_api/api/groups.rb
spec/discourse_api/api/groups_spec.rb

As discussed in https://meta.discourse.org/t/discourse-gem-group-add/25668.

Update add and remove group calls for changed discourse API

---

examples/backups.rb
lib/discourse_api/api/backups.rb

Download and upload backup file is a WIP.

FEATURE: create and restore backup

---

examples/dashboard.rb
lib/discourse_api/api/dashboard.rb
lib/discourse_api/client.rb

Add Dashboard Stats

---

.travis.yml
discourse_api.gemspec

updated rack dependency for rails 5. rails 5 depends on rack 2.

updated rack dependency and added ruby 2.3 to travis config

---

lib/discourse_api/api/groups.rb
spec/discourse_api/api/groups_spec.rb
spec/fixtures/members_0.json
spec/fixtures/members_1.json

Allow to retrieve more than 100 users with pagination (offset & limit)

Add group_members to list all members of a group

---

examples/create_update_category.rb
lib/discourse_api/api/categories.rb

Add categories#update_category

add update_category def, example

---

examples/badges.rb

Here's an example for managing badges. Hope this is useful!

Examples for badges

---

lib/discourse_api/api/users.rb
spec/discourse_api/api/users_spec.rb

Use the right argument for suspend according to the docs.
https://docs.discourse.org/#tag/Admin%2Fpaths%2F~1admin~1users~1%7Bid%7D~1suspend%2Fput

Use the right argument for Users#suspend

---

examples/group_set_user_notification_level.rb
lib/discourse_api/api/groups.rb

- Group Notifications Endpoint Added for updating user's notification level
- Update to Default Example provided for single user and single group

Group Notifications Endpoint Added + Example

---

examples/category.rb
lib/discourse_api/api/categories.rb

Extended the API with a category_set_user_notification_level endpoint method and example.

Added category_set_user_notification_level endpoint method and example

---

.travis.yml
discourse_api.gemspec

As discussed here https://github.com/discourse/discourse_api/pull/171 we are upgrading the `bundler` version 🚀

Upgrade bundler version

---

lib/discourse_api/api/groups.rb
spec/discourse_api/api/groups_spec.rb

Replaces PR#178
- Group notifications tests
- removed unnecessary return

Group Notification Tests

---

spec/discourse_api/api/api_key_spec.rb
spec/discourse_api/api/backups_spec.rb
spec/discourse_api/api/badges_spec.rb
spec/discourse_api/api/categories_spec.rb
spec/discourse_api/api/email_spec.rb
spec/discourse_api/api/groups_spec.rb
spec/discourse_api/api/notifications_spec.rb
spec/discourse_api/api/polls_spec.rb
spec/discourse_api/api/posts_spec.rb
spec/discourse_api/api/private_messages_spec.rb
spec/discourse_api/api/search_spec.rb
spec/discourse_api/api/site_settings_spec.rb
spec/discourse_api/api/sso_spec.rb
spec/discourse_api/api/topics_spec.rb
spec/discourse_api/api/uploads_spec.rb
spec/discourse_api/api/user_actions_spec.rb
spec/discourse_api/api/users_spec.rb
spec/discourse_api/client_spec.rb
spec/spec_helper.rb

- Per request: [Building Tests for New discourse_api Endpoints](https://meta.discourse.org/t/building-tests-for-new-discourse-api-endpoints/118639).

Test hostname extraction

---

lib/discourse_api/client.rb
spec/discourse_api/client_spec.rb

- Faraday::ClientError for new version of Faraday

Faraday::ClientError update

---

README.md
lib/discourse_api/client.rb

Usage:
```ruby
client.basic_auth = {
user: "test",
password: "secret"
}
```

FEATURE: Add basic auth support

---

CHANGELOG.md
lib/discourse_api/version.rb

Version bump

---

examples/invite_users.rb
lib/discourse_api/api/invite.rb
spec/discourse_api/api/topics_spec.rb

@oblakeerickson Does this PR looks okay? If yes I'll start with the rspecs

DEV: separates required & optional params in invite module

---

examples/invite_users.rb
lib/discourse_api/api/invite.rb
spec/discourse_api/api/invite_spec.rb

DEV: Adds method to update an invite

---

examples/invite_users.rb
lib/discourse_api/api/invite.rb
spec/discourse_api/api/invite_spec.rb

DEV: adds method to destroy all expired invites

---

examples/invite_users.rb
lib/discourse_api/api/invite.rb
spec/discourse_api/api/invite_spec.rb

DEV: Adds more invites methods

---

lib/discourse_api/api/groups.rb
spec/discourse_api/api/groups_spec.rb

Added two new methods for adding or removing group owners and updated some outdated params for the update user method.

Add group owner add and remove methods

---

lib/discourse_api/api/categories.rb
spec/discourse_api/api/categories_spec.rb

Added reorder_categories to call /categories/reorder endpoint.

added reorder_categories

---

lib/discourse_api/api/categories.rb
spec/spec_helper.rb

https://docs.discourse.org/#tag/Categories/operation/createCategory

Only require needed params
