discourse/discourse_api

lib/discourse_api/api/groups.rb, spec/discourse_api/api/groups_spec.rb
See https://meta.discourse.org/t/discourse-add-group-api/25571 for the discussion of this.
=> This fixes the create_group method to remove the root element

examples/groups.rb
The example is missing the 'username' and 'user_id' labels for removing users from groups.
=> Add missing labels in groups example

examples/disposable_invite_tokens.rb
[reported here](https://meta.discourse.org/t/generating-disposable-invite-tokens/17563/6?u=techapj)
=> FIX: disposable invite token example was returning undefined method error

lib/discourse_api/api/sso.rb, lib/discourse_api/single_sign_on.rb
sync_sso should now also support :avatar_url, :avatar_force_update, and :suppress_welcome_message.
I have also brought DiscourseApi::SingleSignOn up to date with the version at https://github.com/discourse/discourse/blob/master/lib/single_sign_on.rb to support the parameters locally.
=> Update SSO params to respect missing parameters

discourse_api.gemspec
We are using the gem in a project that uses a later version of Faraday so we're having Gemfile version conflicts.  The pull request allows patches to Faraday, which is probably a good idea for other reasons as well.
=> Lock to Faraday minor version

discourse_api.gemspec
`discourse_api` specifies `dotenv ~> 1.0` as a runtime dependency. This is a problem when applications bundling `dotenv 2.0` attempt to also bundle `discourse_api`. `dotenv 2.0.0` was released Mar 5, 2015.
Firstly, I've extended the version spec from `~> 1.0` (effectively `>= 1.0, < 2.0`) to `>= 1.0, < 3.0`, thus permitting v2.x which [has no notable breaking changes](https://github.com/bkeepers/dotenv/blob/master/Changelog.md#200---mar-5-2015) that I can see.
Secondly, I don't think an API client library should be declaring `dotenv` as a runtime dependency at all, so I've made it a development dependency. This commit can be omitted if anybody disagrees with that.
=> dotenv 2.0, development dependency

examples/groups.rb, lib/discourse_api/client.rb
I had a problem with discourse_api gem on a new Rails app -
my app just crashed with this error after I added the gem to my Gemfile:
```
/Users/user/.rvm/gems/ruby-2.2.2/gems/discourse_api-0.4.3/lib/discourse_api/client.rb:1:in `require': cannot load such file -- dotenv (LoadError)
```
I think it's because dotenv is a development dependency in gemspec,
yet we have a require 'dotenv' in client.rb. It's never loaded by
bundler when the gem is just added to a gem file, so the app crashes.
I don't see it being used in client.rb, so I've deleted it.
It's used in examples/groups.rb so I've added the require there.
I'm not sure if we need dotenv at all, can someone comment on it?
=> Removed require 'dotenv' since it's not used (?).

lib/discourse_api/api/categories.rb, spec/discourse_api/api/categories_spec.rb
In order to make a category private to a certain group upon creation, I have am adding permissions as an optional parameter.  You will need to have the group name and a permission_type.  I am also adding a scenario to test creating a category.
Permission types are:
1 = Full
2 = Create Post
3 = Read Only
Example use:
response = @client.create_category(
name: “CategoryName”,
color: "283890"
text_color: "FFFFFF",
description: "This is a description",
permissions: {"group_1" => 1, "admins" => 1}
)
=> Adding permissions to create a category

spec/discourse_api/api/categories_spec.rb
Eventually I would like to create some integration tests that actually talk
to a discourse instance, but for these current rspec tests we need them
to run without requiring a local instance of discourse to be running and
to be in just the right state for the tests to pass. Not having the
tests actually talk to discourse will also let us use Travis for testing.
The following changes were made:
- stub out the create category test
- broke up some really long lines
=> Ensure tests don't require discourse to be running

examples/category.rb, lib/discourse_api/api/categories.rb, lib/discourse_api/api/params.rb, lib/discourse_api/api/topics.rb, spec/discourse_api/api/categories_spec.rb
- Be able to get topics in a category by page
- `category_latest_topics` now takes a params hash instead of a string
- Added example
- changed url to be '/c/' instead of '/category/'
- Updated test to use new url and params hash
=> Add support for getting category topics by page

lib/discourse_api/api/topics.rb
Added new method for fetching a chunk of posts that belong to a topic.
Currently if you called `client.topic('topic_id')` you would only get
back ~20 posts.
Now you can call `client.topic_posts('topic_id', post_ids)` to get all
the posts you specify in the `post_ids` array.
=> fetch a group of posts that belong to a topic

lib/discourse_api/api/params.rb, spec/discourse_api/api/params_spec.rb
The `to_h` method for `API::Params` does not work correctly when both the `optional` and `default` methods are called.
When trying to create a category via `create_category`, it is defined as allowing:
args = API.params(args)
.required(:name, :color, :text_color)
.optional(:description, :permissions)
.default(parent_category_id: nil)
If you specify a `parent_category_id` in the original `args`, it will be overwritten with `nil` when the `to_h` method is called to perform the request.
The `to_h` method processed the `optional` and `default` params by:
h =
if @optional.length == 0
@args.dup
else
@optional.each do |k|
h[k] = @args[k] if @args.include?(k)
end
h
end
@defaults.each do |k,v|
h[k] = v unless h.key?(k)
end
If optional values are specified, any default keys present in `args` are …
=> [FIX] API::Params will not work correctly when both optional and defaults are specified.

lib/discourse_api/client.rb
Currently the gem only allows requests with both an API key and username present. Even though, they can be `nil` by default, attempting to access a public route in Discourse such as `/categories.json` will raise an authentication error.
This change will allow public access of routes such as categories or latest topics without compromising the security of actions like making a new post  or user-specific visibility settings. It's virtually identical to a direct `curl` request against a Discourse app.
=> Add ability for public, unauthed users

examples/post_action.rb, lib/discourse_api/api/posts.rb, lib/discourse_api/api/topics.rb
This PR adds post actions, which include likes and the different types of flags based on the ID that's passed in. They can be created, destroyed and retrieved for a specific post along with the user that committed the action.
Thoughts? Feedback much appreciated!
=> Add post actions such as likes and flags

examples/post_action.rb, lib/discourse_api/api/posts.rb, lib/discourse_api/api/topics.rb
I made a derp and wrote `post_id` and `topic_id` instead of `id` for the new post action methods. The Discourse app requires the `id` as a parameter for the post actions controller. Sorry!
=> FIX: Use id instead of topic_id or post_id in params for post actions

lib/discourse_api/api/topics.rb
This is a missing piece of functionality which is the best current way to set the timestamp upon a new topic, as it cannot be specified when a topic is created.
For reference please see:
* https://meta.discourse.org/t/set-the-date-of-a-new-topic-via-the-api/43308
=> Allow topic-creation-times to be edited.

examples/backups.rb, lib/discourse_api/api/backups.rb
THe default download is not very useful and likely not working
out of the box most of the time.
=> Add a destination parameter to download_backup

lib/discourse_api/api/topics.rb
Currently the username is only set via the client.api_username.  I suspect this is an old carryover from when the Discourse API had both an api_key and api_username?  Either way, you should be able to POST new topics from multiple users and you shouldn't have to create new client connections each time.  In a perfect world the param for create_topic would be 'username' and not 'api_username', but that param is controlled by the Discourse API ¯\_(ツ)_/¯
=> You should be able to set the username of a topic when POSTing a new topic to the API

examples/change_topic_status.rb, lib/discourse_api/api/topics.rb
API should support closing/opening, archiving/unarchiving, etc, a topic.  I added an example and put in some statuses but I may not have captured them all.
=> Allow for changing of topic statuses

.travis.yml, lib/discourse_api/api/posts.rb, spec/discourse_api/api/posts_spec.rb, spec/fixtures/post_action_users.json
- Add a unit test and fixture for post_action_users
- Add a fixture for post_action_users
- Fixture taken from a Discuss 1.6.1 live instance (text values changed)
- Tested locally against current (9/1) master branch on discourse/discourse
=> Update Posts#post_action_users for 1.5 endpoint

lib/discourse_api/api/users.rb, spec/discourse_api/api/users_spec.rb
Tested on Discourse 1.6.4 (latest stable), and those endpoints haven't changed since then on master (they've been stable since last year).
Those endpoints return empty 200s, so I didn't bother making fake fixture files with no resemblance to reality, is that ok?
=> Add wrappers for admin/users/{id}/[suspend|unsuspend] endpoints

examples/upload.rb, lib/discourse_api/api/uploads.rb, lib/discourse_api/client.rb, spec/discourse_api/api/uploads_spec.rb, spec/discourse_api/api/users_spec.rb, spec/fixtures/upload_post_image.json
This adds the ability to upload images via a file or a URL.
We needed a way to upload an image as part of a new post/topic creation. Ideally, this is called first and the URL provided will match what's returned in the newly created cooked post markup.
=> Add upload post image

lib/discourse_api/api/posts.rb, spec/discourse_api/api/posts_spec.rb
Simply adds a method for deleting a post, similar to the one for topics.
=> Add delete_post method

lib/discourse_api/client.rb, lib/discourse_api/error.rb, spec/discourse_api/api/users_spec.rb
We found that only having an unauthenticated or generic error was a bit too vague for our needs. I've added some common ones including `NotFound`, `UnprocessableEntity`, and `TooManyRequests`, which is returned when the rate limit is hit on the Discourse instance.
=> Add more specific errors

discourse_api.gemspec
The latest [`discourse_api` v0.14.0](https://rubygems.org/gems/discourse_api/versions/0.14.0) depends on `rack ~> 1.6` while [Rails 5's `actionpack`](https://rubygems.org/gems/actionpack/versions/5.0.0.1) depends on `rack ~> 2.0`, so `discourse_api` is holding back upgrades to Rails 5. Bundler tends to resolve this by using [`discourse_api` v0.10.1](https://rubygems.org/gems/discourse_api/versions/0.10.1) (it depends on `rack >= 1.5`) which isn't a desirable resolution.
I doubt there's any changes in Rack v2.x that are incompatible with `discourse_api`; the stricter version spec came in e2d3ce7c5d2f8e663dc1539e0909547831a800a8 which doesn't mention it as a deliberate change.
This PR changes the dependency to `rack >= 1.6`, thus leaving the lower-bound unchanged but permitting newer …
=> rack dependency loosened to permit rack v2 / Rails v5.

examples/create_private_message.rb, lib/discourse_api/api/private_messages.rb, spec/discourse_api/api/private_messages_spec.rb
Allows to create private messages via API as requested in #140 
API reference: http://docs.discourse.org/#tag/Topics
=> Create private messages

lib/discourse_api/client.rb, spec/discourse_api/client_spec.rb
When the remote server returns a 500-599 error status, the API returns an empty or string based body, breaking methods that depend on a structured response (such as `Topics#latest_topics`) in unexpected or hard-to-handle ways.
Instead, we could/should handle these with a known, consistent error code to ease handling. The changes add a case statement to the method in the base client library that parses response codes, looks for anything in the 500…600 range, and raises a DiscourseApi::Error.
=> Add connection error handling for 500 responses

README.md, examples/create_private_message.rb, examples/sent_private_messages.rb, lib/discourse_api/api/private_messages.rb, spec/discourse_api/api/private_messages_spec.rb
This PR adds the ability to fetch the private messages sent by the user. 
API Reference: [Sent Private Messages](http://docs.discourse.org/#tag/Private-Messages%2Fpaths%2F~1topics~1private-messages-sent~1%7Busername%7D.json%2Fget)
=> Fetch sent private messages

lib/discourse_api/api/sso.rb, lib/discourse_api/single_sign_on.rb
Title synchronization was added to the SSO functionality in
https://github.com/discourse/discourse/pull/4681
This allows us to gameify title acquisition, and programatically update
user titles.
Let me know if I need to change, add or delete anything, or if this isn't right for now.
Thanks!
=> Add Title To SSO Synchronization

lib/discourse_api/api/groups.rb, spec/discourse_api/api/groups_spec.rb, spec/spec_helper.rb
This PR does two things:
1) Fixes the `create_group` API call to send up params like `group[name]` as (newly?) required by Discourse. Previously, they were getting sent up as `name`, and `create_group` was failing. I also added the rest of the optional params as defined in the Admin::GroupsController here: https://github.com/discourse/discourse/blob/master/app/controllers/admin/groups_controller.rb#L193
2) Creates an `update_group` API call that updates groups.
=> Create and update groups

lib/discourse_api/api/groups.rb, spec/discourse_api/api/groups_spec.rb, spec/fixtures/group.json
Add a `#group` method that takes a `group_name` as an argument and hits `/groups/<group_name>.json`.
=> Adding the `group` method, which finds a group by name

lib/discourse_api/error.rb
Catch all API errors with a single `rescue DiscourseApi::DiscourseError => error`.
A la https://github.com/stripe/stripe-ruby/blob/master/lib/stripe/errors.rb#L39
=> Adds base error class

lib/discourse_api/client.rb, spec/discourse_api/client_spec.rb
Faraday client strips out any subdirectory path in the host if there is
a leading slash in the request. This change checks if the Discourse host
has a subdirectory, and strips out the leading slash on every
GET/POST/PUT/DELETE request to allow for subdirectories.
E.g.
**Old Behaviour**
When running `client.latest_topics`
Host: `http://www.myblog.com/discourse`
Expected: `http://www.myblog.com/discourse/latest.json`
Actual: `http://www.myblog.com/latest.json`
**New Behaviour**
When running `client.latest_topics`
Host: `http://www.myblog.com/discourse`
Expected: `http://www.myblog.com/discourse/latest.json`
Actual: `http://www.myblog.com/discourse/latest.json`
=> Add support for relative paths

README.md, lib/discourse_api/client.rb, lib/discourse_api/error.rb
I added the faraday `env` response to `handle_error` error initialization. I was finding that passing response.env[:body] to the "message" slot of the discourse errors automatically called "to_s" on the response. So if you wanted to use `{ errors: [' Name has already been taken'] }` as a hash, you'd have to additionally parse that string (`"{\"errors\"=>[\"Name has already been taken\"]}"`).
With this change, this is possible:
```ruby
begin
@client.create_group(args)
rescue DiscourseApi::UnprocessableEntity => error
puts error.response.body['errors'].first
end
```
where previously `error.message` would've been `"{\"errors\"=>[\"Name has already been taken\"]}"` which you would've had to parse with `eval` or something similar (see: …
=> Adds faraday response env to errors

lib/discourse_api/api/sso.rb
This PR allows the `add_groups` and `remove_groups` properties to be set by `sync_sso`. If required, I can add a test to this early next week.
Related topic on meta: https://meta.discourse.org/t/sync-sso-returns-user-info-but-doesnt-update/103583.
=> FEATURE: Add add_groups and remove_groups to sync_sso

lib/discourse_api/api/users.rb
To allow search and pagination the list_users method need to support receiving extra params that will be passed to the API endpoint (which already supports a series of params).
=> Adding params to users#list_users

lib/discourse_api/client.rb
Some undocumented API endpoints that use POST actually return as 201 but the gem interprets as an error. For example: `POST admin/themes/import`.
By the same token, 204 can be a valid POST response as per [this](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.5), so this should not be considered an error either.
=> Add 201 Created and 204 No Content as valid POST responses

lib/discourse_api/api/categories.rb
Add `custom_fields` param to create_category and update_category api calls to allow use of plugins through api calls
=> Include `custom_fields` params in category calls

examples/polls.rb, lib/discourse_api/api/polls.rb, lib/discourse_api/client.rb, spec/discourse_api/api/polls_spec.rb, spec/fixtures/polls_toggle_status.json, spec/fixtures/polls_vote.json, spec/fixtures/polls_voters.json
- poll vote
- toggle poll status
- poll voters
- RuboCop Fixes
=> - Created 3 poll methods for endpoints

lib/discourse_api/api/badges.rb, spec/discourse_api/api/badges_spec.rb
- user-badges endpoint for full badges list
-   vs. /u/user_name/activity/badges, which gave partial list
- tests
=> user-badges endpoint

lib/discourse_api/api/users.rb
- Not the complete list, but best we can do for now given the use of .optional to control the possible values and contributors submitting expansions to that list based on their own needs.
- Unfortunately update_user fails silently when a non-allowed value is tried in the api.
=> Expanded list of allowed messages

lib/discourse_api/single_sign_on.rb
Thats allows us to set the locale when we use Discourse with multilingual system.
=> Allow to set locale in SingleSignOn

lib/discourse_api/api/groups.rb, spec/discourse_api/api/groups_spec.rb, spec/fixtures/members_2.json
including owners.
Currently the actual Discourse API returns a hash with the keys "members, owners, and meta"
The current implementation in this discourse_api gem returns only "members". I added an optional argument `all` that can be passed to `#group_members` so we can get `members`,  and `owners`
=> added optional param :all to #group_members so we can return all members

lib/discourse_api/api/categories.rb, lib/discourse_api/api/params.rb, lib/discourse_api/api/topics.rb, spec/discourse_api/api/params_spec.rb, spec/discourse_api/api/topics_spec.rb
- Fix bug with required params that are `false`.
* `ArgumentError` was raised in this case.
- Allow more optional parameters when creating a category.
* I'm not sure why these params weren't already listed as optional. I tested specifying a `slug` and it gets set correctly, so it looks like these optional values will be used to create the category if they are specified.
- Don't require topic slug when updating topic status.
* Update the request to match the route in the docs: https://docs.discourse.org/#tag/Topics/paths/~1t~1{id}~1status/put
=> Updates and fixes for topic and category methods.

lib/discourse_api/api/sso.rb, lib/discourse_api/single_sign_on.rb
When syncing with SSO enabled, some attributes don't get updated - I added `bio`, `profile_background_url` and `card_background_url`.
I hope these are the only places where they need to be added? I only edited the files directly on github and haven't tested yet.
=> Add attributes to sync_sso method

README.md
The `hot_topics` method was removed in 1c1fcbf0a34c527a7a3e98b28fd1810cc5a6fcdb and seemingly added back to the `README.md` in fbbb11fe149ba8ae9fe367bb616f5b6d814b6b15. This removes it again as it no longer exists in the codebase.
Ideally a new [`top_topics`](https://docs.discourse.org/#tag/Topics/paths/~1top.json/get) method should be added as a replacement, c.f a3cb6adbed7c8769dcf62c5fe7dcb6d1d7488b15
=> hot_topics method no longer exists

CHANGELOG.md, discourse_api.gemspec
The support for Ruby 2.3 has ended in March 2019 (https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/) and Ruby 2.4 is no longer supported as of April 2020 (https://www.ruby-lang.org/en/news/2020/04/05/support-of-ruby-2-4-has-ended/)
We already don't test against those versions in our CI setup.
This fixes (I hope) the build-breaking rubocop error:
"RuboCop found unsupported Ruby version 2.2 in `required_ruby_version` parameter (in discourse_api.gemspec). 2.2-compatible analysis was dropped after version 0.68.
Supported versions: 2.4, 2.5, 2.6, 2.7, 3.0"
=> Require Ruby >= 2.5

lib/discourse_api/api/tags.rb
The legacy "tags" route was removed recently:
https://meta.discourse.org/t/-/169414/5?u=blake
=> FIX: Update to use new tag endpoint

lib/discourse_api/api/users.rb
[API supports](https://docs.discourse.org/#tag/Users/paths/~1users/post) sending the `approved` option to `POST /users`.
=> Support passing approved to #create_user

examples/category.rb, lib/discourse_api/api/categories.rb, spec/discourse_api/api/categories_spec.rb
This is not a fully flushed out PR but enough to get a conversation going around the neglected metadata when fetching categories.
Essentially, I'm trying to access metadata on category response, not just the categories/topics within. Specifically, `can_create_topic` and other permissions, eg:
https://github.com/discourse/discourse_api/blob/74c423c5018cdd8832ba92025fa15ce88790eee0/spec/fixtures/category_latest_topics.json#L10
This would be breaking, of course, but I'm not sure how to accomplish it otherwise. Once we align on direction, I can flush out the remainder and specs.
=> Return full response body when fetching categories

lib/discourse_api/client.rb, lib/discourse_api/error.rb, spec/discourse_api/client_spec.rb
Adds option to set Faraday timeout
```
client = DiscourseApi::Client.new("http://try.discourse.org").tap do |c|
c.timeout = 15
end
```
=> Adds timeout to requests

lib/discourse_api/api/topics.rb, spec/discourse_api/api/topics_spec.rb, spec/fixtures/topic_posts.json
This allows you to pass params to the get `topic_posts` or `/t/:topic_id/posts.json` endpoint
Small change, but I think this captures it all. Let me know if I've missed something.
=> adds params to get topic_posts

lib/discourse_api/api/private_messages.rb, spec/discourse_api/api/private_messages_spec.rb
`create_private_message` has been deprecated to remove the use of the
`target_usernames` parameter. A deprecation warning message will now be
outputed if you use that method. Please use `create_pm` from now on with
the `target_recipients` param.
=> DEPRECATED: create_private_message

lib/discourse_api/error.rb, spec/discourse_api/client_spec.rb
When the timeout is raised by `faraday`, `discourse_api` tries raise `DiscourseApi::Timeout` but it instead raise `ArgumentError (wrong number of arguments (given 0, expected 1..2))`. It raises this because `DiscourseApi::Timeout` inherits from `DiscourseApi::DiscourseError` which explitcly requies `message` arguement on intialization.
Solution: `DiscourseApi::Timeout` should inherit from `DiscourseApi::Error`, as `DiscourseApi::Error` derives exception message from `$!`.
bug repro script:
```ruby
require 'bundler/inline'
gemfile(true) do
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gem 'discourse_api', '~> 0.47.0'
gem 'minitest'
end
require "minitest/autorun"
require "discourse_api"
client = …
```
=> Fixes the timeout error

lib/discourse_api/single_sign_on.rb
`DiscourseApi::SingleSignOn#groups` currently returns an array with a single string that contains all the user's groups comma-concatenated. This API is not very friendly to use, so this PR changes the method to make it return a proper array where each element/string is a group name.
=> FIX: Make `DiscourseApi::SingleSignOn#groups` return a better array

CHANGELOG.md, lib/discourse_api/version.rb
Depends on https://github.com/discourse/discourse_api/pull/243.
=> version bump to 0.48.0, update changelog

lib/discourse_api/single_sign_on.rb, spec/discourse_api/api/sso_spec.rb
Discourse Connect has new attributes in core, so we need to add them in this gem. See core commit https://github.com/discourse/discourse/commit/eb5a3cfded114ad1ef701e9e3f495c98d2f70ebd.
=> DEV: Add new Discourse Connect attributes

CHANGELOG.md, lib/discourse_api/version.rb
To release https://github.com/discourse/discourse_api/pull/245.
=> version bump to 0.48.1

.github/workflows/ci.yml, CHANGELOG.md, discourse_api.gemspec, lib/discourse_api/version.rb
Update minimum ruby to 2.6, update the CI workflow, fix warnings by adding `uri` gem.
=> Version 1.0.0

CHANGELOG.md, lib/discourse_api/single_sign_on.rb, lib/discourse_api/version.rb, spec/discourse_api/single_sign_on_spec.rb
@tgxworld I went with bumping the minor version, but should we do a major version bump? Some consumers may be too specific and expect the `parse` method to raise `RuntimeError`, so I'm not completely sure.
=> FEATURE: Change error raised by the SSO parse method to a custom error class

lib/discourse_api/api/users.rb, lib/discourse_api/version.rb
Follow-up to https://github.com/discourse/discourse/commit/a157f4aaaa8315e83d5be79e12aa630f11524c20
=> DEV: `invite_admin` endpoint is no longer available in Discourse core.

lib/discourse_api/single_sign_on.rb, spec/discourse_api/single_sign_on_spec.rb
That string typically comes from the end user so it may not contain sso parameter at all
=> Update single_sign_on.rb to avoid 500 errors on malformed sso queries
